import React from 'react';

const PrivacyPolicy: React.FC = () => {
    return (
        <div className="min-h-screen bg-gray-50 dark:bg-[#0F0F0F] text-gray-800 dark:text-gray-200 p-8 md:p-16">
            <div className="max-w-3xl mx-auto space-y-8 animate-reveal">
                <header className="space-y-4 border-b border-gray-200 dark:border-white/10 pb-8">
                    <h1 className="text-4xl font-bold tracking-tight">Privacy Policy</h1>
                    <p className="text-sm text-gray-500 dark:text-gray-400">Last Updated: 2026.02.11</p>
                </header>

                <section className="space-y-4">
                    <p>This Privacy Policy describes how this website ("Service", "we", "us", or "our") collects, uses, and protects personal data when you use our browser start-page web application.</p>
                    <p>This Service is operated by an independent developer and is intended for users located in the European Union, United States, and Canada.</p>
                    <p>By using the Service, you agree to the practices described in this Privacy Policy.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">1. Scope of This Policy</h2>
                    <p>This Policy applies to:</p>
                    <ul className="list-disc pl-5 space-y-2 text-gray-700 dark:text-gray-300">
                        <li>Account registration and authentication</li>
                        <li>User-configured content preferences</li>
                        <li>Custom quick-link management</li>
                        <li>Analytics and infrastructure processing</li>
                    </ul>
                    <p>This Service is designed to collect only the minimum data necessary to operate functionality.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">2. Information We Collect</h2>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">2.1 Account Information</h3>
                        <p>When you sign in using:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Google OAuth (currently supported)</li>
                            <li>Apple Sign-In (planned)</li>
                            <li>Email authentication (planned)</li>
                        </ul>
                        <p>We may collect:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Email address</li>
                            <li>Public display name</li>
                            <li>Authentication identifier</li>
                            <li>Account ID generated by our backend</li>
                        </ul>
                        <p className="text-sm text-gray-500">Authentication is securely managed via Supabase. We do not collect or store passwords when third-party OAuth providers are used.</p>
                    </div>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">2.2 User Preferences and Settings</h3>
                        <p>We store:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Natural language content preferences (e.g., “show me motivational quotes”)</li>
                            <li>Custom quick-link URLs</li>
                            <li>Custom display configurations</li>
                        </ul>
                        <p>This data is stored in Supabase databases.</p>
                        <p>We do not intentionally collect sensitive personal data. Users are advised not to submit sensitive personal information in prompt fields.</p>
                    </div>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">2.3 Content Processing and AI Usage</h3>
                        <p>User preference text may be processed to retrieve or generate content.</p>
                        <p>Where AI services are used:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Prompts are pseudonymized</li>
                            <li>Direct account identifiers are not transmitted</li>
                            <li>Data is processed only to provide requested functionality</li>
                            <li>Prompts are not used to train public AI models</li>
                        </ul>
                        <p>We do not use user data for profiling or automated decision-making that produces legal or significant effects.</p>
                    </div>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">2.4 Website Icon Retrieval</h3>
                        <p>When users add a custom link:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>The browser directly requests publicly available favicon data from the target website.</li>
                            <li>We do not proxy, intercept, or log those requests.</li>
                            <li>We do not monitor or analyze user-added URLs for behavioral tracking.</li>
                        </ul>
                    </div>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">2.5 Analytics</h3>
                        <p>We use Umami, a privacy-focused analytics solution.</p>
                        <p>Umami:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Does not use tracking cookies</li>
                            <li>Does not collect personal identifiers</li>
                            <li>Does not track users across websites</li>
                            <li>Does not store IP addresses in identifiable form</li>
                        </ul>
                        <p>Analytics are used only to understand aggregated usage patterns.</p>
                    </div>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">3. Legal Basis for Processing (GDPR – EU Users)</h2>
                    <p>We process personal data under the following legal bases:</p>
                    <ul className="list-disc pl-5 space-y-2">
                        <li><strong>Article 6(1)(b)</strong> – Performance of a contract (providing the Service)</li>
                        <li><strong>Article 6(1)(f)</strong> – Legitimate interests (service security and improvement)</li>
                        <li><strong>Article 6(1)(a)</strong> – Consent (where required)</li>
                    </ul>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">4. Data Storage and Infrastructure</h2>
                    <p>We use:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li><strong>Vercel</strong> – Hosting and deployment</li>
                        <li><strong>Supabase</strong> – Database and authentication services</li>
                        <li><strong>Google OAuth</strong> – Authentication provider</li>
                    </ul>
                    <p>Data may be processed in the United States or other jurisdictions where these providers operate.</p>
                    <p>Where required, we rely on Standard Contractual Clauses (SCCs) or equivalent data protection safeguards.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">5. Data Sharing</h2>
                    <p>We do not:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>Sell personal data</li>
                        <li>Share personal data for advertising</li>
                        <li>Engage in behavioral advertising</li>
                        <li>Monetize user data</li>
                    </ul>
                    <p>Personal data is shared only with infrastructure providers strictly necessary to operate the Service.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">6. Future Personalization Features</h2>
                    <p>We may introduce optional personalization features in the future, such as:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>Usage frequency metrics</li>
                        <li>Click-based optimization</li>
                        <li>Feature engagement analysis</li>
                    </ul>
                    <p>If implemented, this Privacy Policy will be updated accordingly.</p>
                    <p>No behavioral tracking is currently active.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">7. Data Retention</h2>
                    <p>We retain data:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>While your account remains active</li>
                        <li>Until you request deletion</li>
                    </ul>
                    <p>Inactive accounts may be deleted after prolonged inactivity for security purposes.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">8. Data Deletion</h2>
                    <p>You may request deletion of your account and associated data at any time.</p>
                    <p>To request deletion, contact:</p>
                    <p className="font-medium">Email: dinosamw@gmail.com</p>
                    <p>Upon verified request:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>Account information will be deleted</li>
                        <li>Stored preferences will be permanently removed</li>
                        <li>Authentication tokens will be revoked</li>
                    </ul>
                    <p>Deletion requests are processed within a reasonable timeframe.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">9. Your Rights</h2>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">9.1 European Union (GDPR)</h3>
                        <p>You have the right to:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Access your personal data</li>
                            <li>Rectify inaccurate data</li>
                            <li>Request erasure</li>
                            <li>Restrict processing</li>
                            <li>Object to processing</li>
                            <li>Data portability</li>
                            <li>Lodge a complaint with your supervisory authority</li>
                        </ul>
                    </div>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">9.2 California (CCPA/CPRA)</h3>
                        <p>California residents have the right to:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Know what personal data is collected</li>
                            <li>Request deletion</li>
                            <li>Request correction</li>
                            <li>Opt-out of sale (we do not sell data)</li>
                        </ul>
                    </div>

                    <div className="pl-4 border-l-2 border-gray-200 dark:border-white/10 space-y-4">
                        <h3 className="text-xl font-medium">9.3 Canada (PIPEDA)</h3>
                        <p>Canadian users may:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li>Access their personal data</li>
                            <li>Request correction</li>
                            <li>Withdraw consent</li>
                        </ul>
                    </div>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">10. Children’s Privacy</h2>
                    <p>This Service is intended for users aged 16 or older.</p>
                    <p>We do not knowingly collect personal data from children under 16.</p>
                    <p>If you believe a child has provided personal data, please contact us and we will delete it promptly.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">11. Security Measures</h2>
                    <p>We implement reasonable technical safeguards, including:</p>
                    <ul className="list-disc pl-5 space-y-1">
                        <li>Encrypted HTTPS transmission</li>
                        <li>Secure authentication workflows</li>
                        <li>Database access controls</li>
                        <li>Infrastructure-level protections</li>
                    </ul>
                    <p>However, no internet transmission is completely secure.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">12. International Data Transfers</h2>
                    <p>Because our infrastructure providers operate globally, data may be processed outside your country of residence.</p>
                    <p>Where required, appropriate safeguards are implemented to ensure lawful data transfers.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">13. Changes to This Policy</h2>
                    <p>We may update this Privacy Policy as the Service evolves.</p>
                    <p>Material changes will be reflected in the updated date above.</p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-semibold">14. Contact Information</h2>
                    <p>For privacy-related inquiries or deletion requests, contact:</p>
                    <p className="font-medium text-lg text-indigo-600 dark:text-indigo-400">Email: dinosamw@gmail.com</p>
                </section>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
